### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by wezm** [akhramov/akhramov.github.io#2]
Would be great if your blog had an RSS feed so new posts show up in my reader automatically.

**Comment by akhramov** [comment]
Sure, I'll figure something out :)

**Comment by akhramov** [comment]
#3 introduces atom and rss feeds:
https://akhramov.github.io/atom.xml
https://akhramov.github.io/rss.xml

Please LMK if something's missing.

**Comment by wezm** [comment]
Excellent, thank you. I have subscribed to rss.xml.
